# Generated by Django 3.2.16 on 2022-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('start', 1), ('main', 2), ('service', 3), ('master', 4), ('date', 5), ('registration', 6), ('consent', 7), ('name', 8), ('lk', 9)], max_length=64)),
                ('buttons', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('state', models.CharField(choices=[('start', 1), ('main', 2), ('service', 3), ('master', 4), ('date', 5), ('registration', 6), ('consent', 7), ('name', 8), ('lk', 9)], default='start', max_length=64)),
                ('chosen_service', models.CharField(max_length=120, null=True)),
                ('chosen_master', models.CharField(max_length=120, null=True)),
                ('chosen_date', models.DateTimeField(null=True)),
                ('full_name', models.CharField(max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
